version: "3.8"

services:
  app:
    build: . 
    depends_on:
      - postgres 
      - mongo 
    env_file:
      - .env 
    ports:
      - "3000:3000" 
    networks:
      - backend-net 

  postgres:
    image: postgres:13 
    restart: always 
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: admin 
      POSTGRES_DB: bonsae_database 
    ports:
      - "5432:5432"
    networks:
      - backend-net 
    volumes:
      - pgdata:/var/lib/postgresql/data 
      - ./init-postgres:/docker-entrypoint-initdb.d 

  mongo:
    image: mongo:5.0 
    restart: always 
    ports:
      - "27017:27017"
    networks:
      - backend-net 
    volumes:
      - mongodata:/data/db 

networks:
  backend-net:
    driver: bridge 

volumes:
  pgdata: 
  mongodata: 