version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: bonsae-container
    restart: always
    environment:
      POSTGRES_USER: admin-bonsae
      POSTGRES_PASSWORD: bonsae
      POSTGRES_DB: bonsaeDB
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
