export enum UsuariosPerfilEnum{

  COORDENADOR = 'COORDENADOR',
  COORDENADORA = 'COORDENADORA',
  PROFESSOR = 'PROFESSOR',
  PROFESSORA = 'PROFESSORA',
  ALUNO = 'ALUNO',
  ALUNA = 'ALUNA',
  SECRETARIO = 'SECRETARIO',
  SECRETARIA = 'SECRETARIA',
  ESTAGIARIO = 'ESTAGIARIO',
  ESTAGIARIA = 'ESTAGIARIA',
  ADVOGADO = 'ADVOGADO',
  ADVOGADA = 'ADVOGADA'

}